#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""分类规则配置：平台、类型、生态归属、生态角色"""

# ==================== 平台分类规则 ====================
# 平台 = 操作系统 / 运行时环境，严格区别于应用形态
PLATFORM_RULES = {
    "Android": [
        "android", "apk", "aar", "android-app"
    ],
    "iOS": [
        "ios", "swift", "objective-c", "objc", "iphone", "ipad", "ipa"
    ],
    "Windows": [
        "windows", "win32", "win64", "uwp", "wsl", "winforms", "wpf", "windows-app"
    ],
    "Linux": [
        "linux", "ubuntu", "debian", "fedora", "arch", "gentoo", "redhat", "centos"
    ],
    "macOS": [
        "macos", "mac-os", "osx", "darwin", "apple"
    ],
    "Web": [
        "browser", "web", "html5", "pwa", "webapp"
    ],
    "跨平台": [
        "cross-platform", "multi-platform", "electron", "tauri", "qt", "flutter", "react-native", "xamarin"
    ],
}

# ==================== 类型分类规则 ====================
# 类型 = 应用形态 + 功能角色
TYPE_RULES = {
    "框架 / Framework": ["framework", "library", "sdk", "runtime", "engine"],
    "工具 / Tool": ["tool", "utility", "generator", "builder", "scaffold", "boilerplate", "helper"],
    "应用 / App": ["app", "application", "client", "server", "service", "portal"],
    "Web 前端": [
        "frontend", "react", "vue", "angular", "svelte", "next.js", "nuxt",
        "webpack", "vite", "spa", "ssr", "dom", "browser-ui",
        "tailwind", "bootstrap", "preact", "solidjs", "astro", "remix", "gatsby"
    ],
    "Web 后端": [
        "backend", "api", "server", "rest", "graphql", "web-framework",
        "fastapi", "django", "express", "spring", "flask", "laravel", "nestjs", "gin", "fiber"
    ],
    "移动端 App": [
        "mobile", "ios-app", "android-app", "apk", "ipa",
        "play-store", "app-store", "cordova", "capacitor", "expo", "ionic"
    ],
    "桌面 GUI": [
        "desktop", "gui", "cross-platform-gui",
        "nw.js", "wxwidgets", "gtk", "native-app"
    ],
    "CLI / 终端": [
        "cli", "terminal", "shell", "command-line", "bash", "zsh",
        "powershell", "tmux", "fish", "nushell", "starship"
    ],
    "游戏": [
        "game", "unity", "unreal", "godot", "bevy", "love2d", "cocos",
        "rpg", "fps", "moba", "visual-novel", "launcher",
        "game-engine", "emulator", "retroarch", "rom", "save-editor", "trainer"
    ],
    "编辑器 / IDE": ["editor", "ide", "vscode", "vim", "neovim", "emacs", "jetbrains", "text-editor", "code-editor"],
    "资源合集 / Awesome": ["awesome", "list", "curated", "resources", "awesome-list", "cheatsheet", "roadmap"],
    "语言 / Compiler": ["language", "compiler", "interpreter", "transpiler", "bytecode"],
    "监控 / 可视化": ["monitoring", "dashboard", "visualization", "metrics", "observability", "chart", "plot", "grafana"],
    "自动化 / 工作流": ["automation", "workflow", "integration", "bot", "cron", "scheduler", "n8n", "ifttt"],
    "笔记 / 知识管理": ["notes", "knowledge", "wiki", "markdown", "second-brain", "documentation", "zettelkasten"],
    "算法 / 学习": ["algorithm", "leetcode", "interview", "tutorial", "course", "book", "study"],
    "配置 / Dotfiles": ["dotfiles", "config", "configuration", "settings", "preset", "rc-file"],
    "其他 / 未分类": [],
}

# ==================== 生态归属规则 ====================
ECOLOGY_RULES = {
    "Clash / Mihomo": {
        "name_patterns": ["clash", "mihomo", "sing-box"],
        "desc_patterns": ["mihomo core", "clash core", "sing-box", "clashmeta", "clash meta", "based on clash", "mihomo"],
        "topic_patterns": ["mihomo", "sing-box", "clash-meta"],
        "related_types": ["gui", "config", "rule-set", "dashboard"],
        "core_projects": ["mihomo", "clash", "sing-box"],
    },
    "MPV": {
        "name_patterns": ["mpv"],
        "desc_patterns": ["mpv", "mpv player", "lua script", "mpv plugin"],
        "topic_patterns": ["mpv"],
        "related_types": ["script", "config", "gui", "skin", "theme", "thumbnail"],
        "core_projects": ["mpv"],
    },
    "VS Code": {
        "name_patterns": ["vscode", "vs-code"],
        "desc_patterns": ["vscode extension", "visual studio code", "vs code"],
        "topic_patterns": ["vscode", "vscode-extension"],
        "related_types": ["extension", "theme", "icon-theme", "snippet"],
        "core_projects": ["vscode"],
    },
    "Neovim": {
        "name_patterns": ["nvim", "neovim"],
        "desc_patterns": ["neovim", "nvim plugin", "vim plugin"],
        "topic_patterns": ["neovim", "vim"],
        "related_types": ["plugin", "colorscheme", "config", "lsp"],
        "core_projects": ["neovim"],
    },
    "Obsidian": {
        "name_patterns": ["obsidian"],
        "desc_patterns": ["obsidian plugin", "obsidian theme"],
        "topic_patterns": ["obsidian"],
        "related_types": ["plugin", "theme", "snippet"],
        "core_projects": ["obsidian"],
    },
    "Home Assistant": {
        "name_patterns": ["home-assistant", "hass", "homeassistant"],
        "desc_patterns": ["home assistant", "homeassistant"],
        "topic_patterns": ["home-assistant", "smart-home"],
        "related_types": ["integration", "addon", "theme", "card"],
        "core_projects": ["home-assistant"],
    },
    "Docker": {
        "name_patterns": ["docker"],
        "desc_patterns": ["dockerfile", "docker-compose"],
        "topic_patterns": ["docker-compose", "containers"],
        "related_types": ["image", "compose", "registry"],
        "core_projects": ["docker", "moby"],
    },
    "React": {
        "name_patterns": ["react-"],
        "desc_patterns": ["react component", "react hook", "for react"],
        "topic_patterns": [],
        "related_types": ["component", "hook", "boilerplate"],
        "core_projects": ["react"],
    },
    "Vue": {
        "name_patterns": ["vue-", "nuxt"],
        "desc_patterns": ["vue component", "vue plugin", "for vue", "nuxt", "vuejs"],
        "topic_patterns": [],
        "related_types": ["component", "plugin", "boilerplate"],
        "core_projects": ["vue", "nuxt"],
    },
    "Tailwind CSS": {
        "name_patterns": ["tailwind"],
        "desc_patterns": ["tailwind", "tailwindcss"],
        "topic_patterns": [],
        "related_types": ["plugin", "component", "ui-kit"],
        "core_projects": ["tailwindcss"],
    },
    "FFmpeg": {
        "name_patterns": ["ffmpeg"],
        "desc_patterns": ["ffmpeg", "video processing", "codec"],
        "topic_patterns": ["ffmpeg"],
        "related_types": ["wrapper", "gui", "binding"],
        "core_projects": ["ffmpeg"],
    },
    "qBittorrent": {
        "name_patterns": ["qbittorrent", "qbit"],
        "desc_patterns": ["qbittorrent", "bt client", "qbittorrent web ui"],
        "topic_patterns": ["qbittorrent"],
        "related_types": ["theme", "plugin", "web-ui"],
        "core_projects": ["qbittorrent"],
    },
    "Hyprland": {
        "name_patterns": ["hypr", "waybar", "wofi", "swww"],
        "desc_patterns": ["hyprland", "wayland compositor", "hypr"],
        "topic_patterns": ["hyprland", "wayland"],
        "related_types": ["dotfiles", "config", "theme", "plugin"],
        "core_projects": ["hyprland"],
    },
    "Zsh / Oh-My-Zsh": {
        "name_patterns": ["zsh", "oh-my-zsh", "powerlevel"],
        "desc_patterns": ["zsh", "oh-my-zsh", "zsh plugin", "shell theme"],
        "topic_patterns": ["zsh", "oh-my-zsh"],
        "related_types": ["plugin", "theme", "config"],
        "core_projects": ["oh-my-zsh"],
    },
    "Starship": {
        "name_patterns": ["starship"],
        "desc_patterns": ["starship", "shell prompt"],
        "topic_patterns": ["starship"],
        "related_types": ["preset", "config", "theme"],
        "core_projects": ["starship"],
    },
    "Alacritty": {
        "name_patterns": ["alacritty"],
        "desc_patterns": ["alacritty", "terminal emulator"],
        "topic_patterns": ["alacritty"],
        "related_types": ["theme", "config"],
        "core_projects": ["alacritty"],
    },
    "Kitty": {
        "name_patterns": ["kitty"],
        "desc_patterns": ["kitty terminal", "kitty config"],
        "topic_patterns": ["kitty"],
        "related_types": ["theme", "config", "script"],
        "core_projects": ["kitty"],
    },
    "i3 / Sway": {
        "name_patterns": ["i3", "sway", "polybar", "rofi", "dunst"],
        "desc_patterns": ["i3wm", "swaywm", "tiling window manager"],
        "topic_patterns": ["i3", "sway", "window-manager"],
        "related_types": ["config", "theme", "script", "bar"],
        "core_projects": ["i3", "sway"],
    },
    "AwesomeWM": {
        "name_patterns": ["awesomewm", "awesome-wm"],
        "desc_patterns": ["awesome window manager", "awesomewm"],
        "topic_patterns": ["awesome-wm"],
        "related_types": ["config", "theme", "widget"],
        "core_projects": ["awesome"],
    },
    "OBS Studio": {
        "name_patterns": ["obs", "obs-studio", "streamfx", "input-overlay"],
        "desc_patterns": ["obs plugin", "obs studio", "obs-studio"],
        "topic_patterns": ["obs", "obs-studio"],
        "related_types": ["plugin", "script", "theme"],
        "core_projects": ["obs-studio"],
    },
    "Electron": {
        "name_patterns": ["electron"],
        "desc_patterns": ["electron app", "electron-based", "cross-platform desktop"],
        "topic_patterns": [],
        "related_types": ["app", "tool", "client"],
        "core_projects": ["electron"],
    },
    "Scoop": {
        "name_patterns": ["scoop"],
        "desc_patterns": ["scoop bucket", "scoop manifest", "windows package manager"],
        "topic_patterns": ["scoop"],
        "related_types": ["bucket", "manifest", "package"],
        "core_projects": ["scoop"],
    },
    "Typora": {
        "name_patterns": ["typora"],
        "desc_patterns": ["typora theme", "typora plugin"],
        "topic_patterns": ["typora"],
        "related_types": ["theme", "plugin"],
        "core_projects": ["typora"],
    },
    "Moonlight / Sunshine": {
        "name_patterns": ["moonlight", "sunshine", "apollo"],
        "desc_patterns": ["moonlight", "sunshine stream", "game stream", "nvidia gamestream", "gamestream"],
        "topic_patterns": ["moonlight", "sunshine", "game-streaming"],
        "related_types": ["client", "server", "stream"],
        "core_projects": ["moonlight", "sunshine"],
    },
    "Mihon / Tachiyomi": {
        "name_patterns": ["mihon", "tachiyomi"],
        "desc_patterns": ["mihon", "tachiyomi", "manga reader"],
        "topic_patterns": ["mihon", "tachiyomi", "manga"],
        "related_types": ["extension", "source", "reader"],
        "core_projects": ["mihon", "tachiyomi"],
    },
    "Emby / Jellyfin": {
        "name_patterns": ["emby", "jellyfin"],
        "desc_patterns": ["emby", "jellyfin", "media server", "media-server"],
        "topic_patterns": ["emby", "jellyfin", "media-server"],
        "related_types": ["plugin", "skin", "server"],
        "core_projects": ["emby", "jellyfin"],
    },
    "Bilibili": {
        "name_patterns": ["bilibili", "bbll", "downkyi", "bilitools", "bili-copilot"],
        "desc_patterns": ["bilibili", "哔哩", "third-party bilibili"],
        "topic_patterns": ["bilibili"],
        "related_types": ["client", "downloader", "tool", "plugin"],
        "core_projects": ["bilibili"],
    },
    "Stable Diffusion": {
        "name_patterns": ["stable-diffusion", "sd-webui", "comfyui", "controlnet", "fooocus"],
        "desc_patterns": ["stable diffusion", "comfyui", "diffusion model", "text-to-image", "image generation"],
        "topic_patterns": ["stable-diffusion", "comfyui", "text-to-image", "image-generation"],
        "related_types": ["webui", "model", "extension", "checkpoint"],
        "core_projects": ["stable-diffusion-webui", "comfyui"],
    },
    "Aria2": {
        "name_patterns": ["aria2", "ariang"],
        "desc_patterns": ["aria2", "aria-ng", "aria download"],
        "topic_patterns": ["ariang"],
        "related_types": ["web-ui", "gui", "client"],
        "core_projects": ["aria2"],
    },
    "yt-dlp": {
        "name_patterns": ["yt-dlp", "youtube-dl"],
        "desc_patterns": ["yt-dlp", "youtube downloader", "video downloader", "based on yt-dlp"],
        "topic_patterns": ["yt-dlp", "youtube-downloader"],
        "related_types": ["downloader", "gui"],
        "core_projects": ["yt-dlp"],
    },
    "AList": {
        "name_patterns": ["alist", "openlist"],
        "desc_patterns": ["alist", "file list program", "cloud storage aggregation"],
        "topic_patterns": ["alist", "webdav"],
        "related_types": ["client", "web-ui", "mount"],
        "core_projects": ["alist"],
    },
    "Tailscale / WireGuard": {
        "name_patterns": ["tailscale", "wireguard", "headscale"],
        "desc_patterns": ["tailscale", "wireguard", "mesh vpn", "zero config vpn"],
        "topic_patterns": ["tailscale", "wireguard"],
        "related_types": ["client", "server", "gui"],
        "core_projects": ["tailscale", "wireguard"],
    },
    "Nushell": {
        "name_patterns": ["nushell"],
        "desc_patterns": ["nushell", "nu shell"],
        "topic_patterns": ["nushell"],
        "related_types": ["plugin", "config", "theme"],
        "core_projects": ["nushell"],
    },
    "Homebrew": {
        "name_patterns": ["homebrew"],
        "desc_patterns": ["homebrew", "brew", "macos package manager"],
        "topic_patterns": ["homebrew"],
        "related_types": ["formula", "cask", "tap"],
        "core_projects": ["brew"],
    },
    "RVC / AI Voice": {
        "name_patterns": ["rvc", "so-vits-svc", "fish-speech", "voice-conversion"],
        "desc_patterns": ["voice conversion", "singing voice conversion", "tts", "text-to-speech", "voice clone"],
        "topic_patterns": ["voice-conversion", "tts", "rvc", "text-to-speech"],
        "related_types": ["model", "gui", "webui"],
        "core_projects": ["retrieval-based-voice-conversion-webui", "so-vits-svc", "fish-speech"],
    },
    "SillyTavern": {
        "name_patterns": ["sillytavern"],
        "desc_patterns": ["sillytavern", "llm frontend", "ai roleplay"],
        "topic_patterns": ["sillytavern"],
        "related_types": ["extension", "theme", "script"],
        "core_projects": ["sillytavern"],
    },
    "Notion / AppFlowy": {
        "name_patterns": ["notionnext", "appflowy", "affine"],
        "desc_patterns": ["notion alternative", "notion-powered", "knowledge base", "second brain"],
        "topic_patterns": ["notion", "notion-alternative", "knowledge-base"],
        "related_types": ["theme", "template", "plugin", "blog"],
        "core_projects": ["appflowy", "affine"],
    },
    "RSS / 阅读": {
        "name_patterns": ["rsshub", "folo", "koodo-reader", "readest"],
        "desc_patterns": ["rss reader", "rss hub", "ebook reader", "ebook manager"],
        "topic_patterns": ["rss", "rss-reader", "ebook", "ebook-reader"],
        "related_types": ["reader", "client", "server"],
        "core_projects": ["rsshub", "folo"],
    },
    "localsend": {
        "name_patterns": ["localsend"],
        "desc_patterns": ["localsend", "cross-platform file sharing", "airdrop alternative"],
        "topic_patterns": ["localsend", "file-sharing"],
        "related_types": ["app", "client"],
        "core_projects": ["localsend"],
    },
    "Ventoy": {
        "name_patterns": ["ventoy"],
        "desc_patterns": ["ventoy", "bootable usb", "multiboot usb"],
        "topic_patterns": ["ventoy", "bootable-usb"],
        "related_types": ["tool", "gui"],
        "core_projects": ["ventoy"],
    },
    "Magisk": {
        "name_patterns": ["magisk"],
        "desc_patterns": ["magisk", "magisk module", "root solution"],
        "topic_patterns": ["magisk", "magisk-module"],
        "related_types": ["module", "manager"],
        "core_projects": ["magisk"],
    },
    "V2Ray": {
        "name_patterns": ["v2ray", "v2fly"],
        "desc_patterns": ["v2ray", "v2fly", "v2ray core", "geosite"],
        "topic_patterns": ["v2ray", "v2fly"],
        "related_types": ["core", "config", "rule"],
        "core_projects": ["v2ray-core"],
    },
    "Genshin Impact / 游戏辅助": {
        "name_patterns": ["genshin", "starrail", "honkai", "yuanshen"],
        "desc_patterns": ["genshin impact", "honkai star rail", "原神", "星穹铁道", "game assistant", "auto-play-game"],
        "topic_patterns": ["genshin-impact", "honkai-star-rail", "genshin", "starrail"],
        "related_types": ["assistant", "automation", "script"],
        "core_projects": ["genshin"],
    },
    "HandBrake": {
        "name_patterns": ["handbrake"],
        "desc_patterns": ["handbrake", "video transcoding"],
        "topic_patterns": ["handbrake"],
        "related_types": ["encoder", "transcoder"],
        "core_projects": ["handbrake"],
    },
    "AltStore": {
        "name_patterns": ["altstore"],
        "desc_patterns": ["altstore", "alternative app store", "sideload"],
        "topic_patterns": ["altstore"],
        "related_types": ["app", "installer"],
        "core_projects": ["altstore"],
    },
    "Playnite": {
        "name_patterns": ["playnite"],
        "desc_patterns": ["playnite", "game library manager"],
        "topic_patterns": ["playnite"],
        "related_types": ["launcher", "library"],
        "core_projects": ["playnite"],
    },
    "Everything": {
        "name_patterns": ["everything"],
        "desc_patterns": ["everything search", "file search"],
        "topic_patterns": ["everything"],
        "related_types": ["search", "toolbar"],
        "core_projects": ["everything"],
    },
    "WSL": {
        "name_patterns": ["wsl"],
        "desc_patterns": ["windows subsystem for linux", "wsl distribution"],
        "topic_patterns": ["wsl"],
        "related_types": ["distribution", "tool"],
        "core_projects": ["wsl"],
    },
    "shairport / AirPlay": {
        "name_patterns": ["shairport"],
        "desc_patterns": ["shairport", "airplay audio"],
        "topic_patterns": ["shairport", "airplay"],
        "related_types": ["audio", "player"],
        "core_projects": ["shairport-sync"],
    },
    "ScreenToGif": {
        "name_patterns": ["screentogif"],
        "desc_patterns": ["screentogif", "screen to gif"],
        "topic_patterns": ["screentogif", "gif-recorder"],
        "related_types": ["recorder", "editor"],
        "core_projects": ["screentogif"],
    },
    "Typst": {
        "name_patterns": ["typst"],
        "desc_patterns": ["typst", "typesetting system"],
        "topic_patterns": ["typst"],
        "related_types": ["compiler", "editor", "template"],
        "core_projects": ["typst"],
    },
    "EhViewer": {
        "name_patterns": ["ehviewer"],
        "desc_patterns": ["ehviewer", "e-hentai"],
        "topic_patterns": ["ehviewer", "e-hentai"],
        "related_types": ["client", "reader"],
        "core_projects": ["ehviewer"],
    },
    "PicaComic": {
        "name_patterns": ["picacomic"],
        "desc_patterns": ["picacomic", "comic app"],
        "topic_patterns": ["picacomic", "comic"],
        "related_types": ["client", "reader"],
        "core_projects": ["picacomic"],
    },
    "Anime4K": {
        "name_patterns": ["anime4k"],
        "desc_patterns": ["anime4k", "anime upscaler", "real time upscaler"],
        "topic_patterns": ["anime4k", "anime-upscaling"],
        "related_types": ["shader", "filter", "upscaler"],
        "core_projects": ["anime4k"],
    },
    "rufus": {
        "name_patterns": ["rufus"],
        "desc_patterns": ["rufus", "usb formatting", "bootable drives"],
        "topic_patterns": ["rufus", "bootable-drives"],
        "related_types": ["tool"],
        "core_projects": ["rufus"],
    },
    "Spotube": {
        "name_patterns": ["spotube"],
        "desc_patterns": ["spotube", "spotify client"],
        "topic_patterns": ["spotube", "spotify"],
        "related_types": ["client", "player"],
        "core_projects": ["spotube"],
    },
    "open-ani / Animeko": {
        "name_patterns": ["animeko", "open-ani"],
        "desc_patterns": ["animeko", "open-ani", "bangumi", "弹幕追番"],
        "topic_patterns": ["anime", "bangumi"],
        "related_types": ["client", "player"],
        "core_projects": ["animeko"],
    },
    "Czkawka": {
        "name_patterns": ["czkawka"],
        "desc_patterns": ["czkawka", "find duplicates", "similar images"],
        "topic_patterns": ["czkawka", "duplicates"],
        "related_types": ["tool", "cleaner"],
        "core_projects": ["czkawka"],
    },
    "TrafficMonitor": {
        "name_patterns": ["trafficmonitor"],
        "desc_patterns": ["traffic monitor", "network speed", "cpu monitor"],
        "topic_patterns": ["traffic-monitor", "network-monitor"],
        "related_types": ["tool", "widget"],
        "core_projects": ["trafficmonitor"],
    },
    "QtScrcpy / Scrcpy": {
        "name_patterns": ["scrcpy", "qtscrcpy"],
        "desc_patterns": ["scrcpy", "qtscrcpy", "mirror your android"],
        "topic_patterns": ["scrcpy"],
        "related_types": ["tool", "gui"],
        "core_projects": ["scrcpy"],
    },
    "TrollStore": {
        "name_patterns": ["trollstore"],
        "desc_patterns": ["trollstore", "ios app installer", "jailed ios"],
        "topic_patterns": ["trollstore"],
        "related_types": ["tool", "installer"],
        "core_projects": ["trollstore"],
    },
    "KernelSU": {
        "name_patterns": ["kernelsu"],
        "desc_patterns": ["kernelsu", "android root", "kernel-based root"],
        "topic_patterns": ["kernelsu", "android-root"],
        "related_types": ["module", "manager"],
        "core_projects": ["kernelsu"],
    },
    "LSPosed": {
        "name_patterns": ["lsposed", "xposed"],
        "desc_patterns": ["lsposed", "xposed framework", "android hook"],
        "topic_patterns": ["lsposed", "xposed"],
        "related_types": ["module", "framework"],
        "core_projects": ["lsposed"],
    },
    "Telegram": {
        "name_patterns": ["telegram", "tdesktop", "ayugram"],
        "desc_patterns": ["telegram client", "telegram desktop", "telegram app"],
        "topic_patterns": ["telegram", "telegram-client"],
        "related_types": ["client", "mod", "theme"],
        "core_projects": ["telegram"],
    },
    "Steam": {
        "name_patterns": ["steam", "millennium"],
        "desc_patterns": ["steam client", "steam theme", "steam plugin", "steam mod"],
        "topic_patterns": ["steam"],
        "related_types": ["theme", "plugin", "mod", "skin"],
        "core_projects": ["steam"],
    },
    "EDK2": {
        "name_patterns": ["edk2"],
        "desc_patterns": ["edk2", "uefi firmware", "tianocore"],
        "topic_patterns": ["edk2", "uefi-firmware"],
        "related_types": ["port", "driver"],
        "core_projects": ["edk2"],
    },
    "fcitx": {
        "name_patterns": ["fcitx"],
        "desc_patterns": ["fcitx", "input method"],
        "topic_patterns": ["fcitx", "fcitx5"],
        "related_types": ["ime", "keyboard", "engine"],
        "core_projects": ["fcitx"],
    },
    "Git": {
        "name_patterns": ["lazygit", "git-extras", "gitui"],
        "desc_patterns": ["git commands", "git tui", "git client", "git tools"],
        "topic_patterns": ["git"],
        "related_types": ["client", "gui", "tool"],
        "core_projects": ["git"],
    },
    "Firefox": {
        "name_patterns": ["firefox", "zen-browser"],
        "desc_patterns": ["firefox", "firefox-based", "firefox browser"],
        "topic_patterns": ["firefox", "firefox-based"],
        "related_types": ["browser", "extension", "theme"],
        "core_projects": ["firefox"],
    },
    "neofetch / fastfetch": {
        "name_patterns": ["neofetch", "fastfetch"],
        "desc_patterns": ["neofetch", "fastfetch", "system information"],
        "topic_patterns": ["neofetch", "fastfetch"],
        "related_types": ["theme", "config"],
        "core_projects": ["neofetch", "fastfetch"],
    },
    "IPTV / 直播": {
        "name_patterns": ["iptv", "my-tv", "mytv", "simple-live"],
        "desc_patterns": ["iptv", "电视直播", "live streaming", "tv live"],
        "topic_patterns": ["iptv", "live-streaming"],
        "related_types": ["player", "client", "app"],
        "core_projects": ["iptv"],
    },
    "Office": {
        "name_patterns": ["office-tool"],
        "desc_patterns": ["office tool", "microsoft office", "office 365", "office deployment"],
        "topic_patterns": ["office", "office-365", "msoffice"],
        "related_types": ["tool", "activator", "installer"],
        "core_projects": ["office"],
    },
    "思维导图 / 白板": {
        "name_patterns": ["mind-map", "mindmap", "xmind", "whiteboard", "drawnix"],
        "desc_patterns": ["mind map", "mind mapping", "whiteboard", "思维导图", "flowchart"],
        "topic_patterns": ["mind-map", "mindmap", "whiteboard", "flowchart"],
        "related_types": ["editor", "template", "tool"],
        "core_projects": ["mind-map"],
    },
    "BitTorrent": {
        "name_patterns": ["trackerslist"],
        "desc_patterns": ["bittorrent tracker", "torrent tracker", "public tracker"],
        "topic_patterns": ["bittorrent", "bittorrent-tracker", "torrent"],
        "related_types": ["tracker", "list"],
        "core_projects": ["trackerslist"],
    },
}

# 已确认准确的生态，AI 批量分析时不会覆盖这些生态下的项目分类
# 用法示例: ["Clash / Mihomo 生态", "Neovim 生态", "VS Code 生态"]
LOCKED_ECOLOGIES = []

ECOLOGY_ROLES = {
    "核心 / Core": ["core", "kernel", "engine", "official"],
    "GUI 前端 / Client": ["gui", "client", "app", "desktop", "frontend", "verge", "nyanpasu", "party"],
    "配置 / Config": ["config", "configuration", "dotfiles", "settings", "preset"],
    "脚本 / Script": ["script", "lua", "python-script", "automation"],
    "主题 / Theme": ["theme", "skin", "color-scheme", "appearance", "icon-theme"],
    "插件 / Plugin": ["plugin", "extension", "addon", "integration"],
    "规则集 / Rules": ["rule", "rule-set", "filter", "list", "blocklist"],
    "Web UI / Dashboard": ["web-ui", "dashboard", "panel", "web"],
    "API 封装 / Wrapper": ["wrapper", "binding", "sdk", "api"],
    "教程 / Guide": ["guide", "tutorial", "awesome", "collection", "list"],
}

# ==================== 生态名称归一化 ====================
# LLM 返回的 ecology 是自由文本，容易产生 "Clash"/"Clash Meta"/"Clash / Mihomo 生态" 等变体。
# 后处理阶段用此表统一映射到标准名称。
ECOLOGY_ALIASES = {
    # Bilibili
    "b站": "Bilibili", "bilibili": "Bilibili", "哔哩哔哩": "Bilibili",
    # Clash / Mihomo（所有变体统一为简洁名称）
    "clash": "Clash / Mihomo", "clash meta": "Clash / Mihomo", "clashmeta": "Clash / Mihomo",
    "mihomo": "Clash / Mihomo", "mihomo 生态": "Clash / Mihomo",
    "clash / mihomo": "Clash / Mihomo", "clash / mihomo 生态": "Clash / Mihomo",
    "clash生态": "Clash / Mihomo", "clash 生态": "Clash / Mihomo",
    "sing-box": "Clash / Mihomo", "sing-box 生态": "Clash / Mihomo",
    # Docker
    "docker 生态": "Docker", "docker生态": "Docker", "container": "Docker",
    # AI/ML
    "ai": "AI/ML", "ai agents": "AI/ML", "ai/ml": "AI/ML", "人工智能": "AI/ML",
    # 独立项目
    "standalone": "独立项目", "none": "独立项目", "null": "独立项目",
    "独立项目 / standalone": "独立项目", "独立": "独立项目",
    # 其他常见变体（去"生态"后缀统一）
    "android 生态": "Android", "apple 生态": "Apple", "苹果": "Apple",
    "ffmpeg": "FFmpeg", "ffmpeg 生态": "FFmpeg", "ffmpeg生态": "FFmpeg",
    "magisk": "Magisk", "magisk 生态": "Magisk",
    "v2ray": "V2Ray", "v2fly": "V2Ray", "v2ray 生态": "V2Ray",
    "genshin": "Genshin Impact / 游戏辅助", "genshin impact": "Genshin Impact / 游戏辅助",
    "genshin 生态": "Genshin Impact / 游戏辅助", "starrail": "Genshin Impact / 游戏辅助",
    "handbrake": "HandBrake", "handbrake 生态": "HandBrake",
    "altstore": "AltStore", "altstore 生态": "AltStore",
    "playnite": "Playnite", "playnite 生态": "Playnite",
    "everything": "Everything", "everything 生态": "Everything",
    "wsl": "WSL", "wsl 生态": "WSL",
    "shairport": "shairport / AirPlay", "airplay": "shairport / AirPlay",
    "shairport 生态": "shairport / AirPlay",
    "git": "Git", "git 生态": "Git",
    "firefox": "Firefox", "firefox 生态": "Firefox", "zen-browser": "Firefox",
    "neofetch": "neofetch / fastfetch", "fastfetch": "neofetch / fastfetch",
    "neofetch 生态": "neofetch / fastfetch", "fastfetch 生态": "neofetch / fastfetch",
    "iptv": "IPTV / 直播", "iptv 生态": "IPTV / 直播", "直播": "IPTV / 直播",
    "office": "Office", "office 生态": "Office",
    "mind-map": "思维导图 / 白板", "mindmap": "思维导图 / 白板", "whiteboard": "思维导图 / 白板",
    "思维导图": "思维导图 / 白板",
    "bittorrent": "BitTorrent", "bittorrent 生态": "BitTorrent",
    "trackerslist": "BitTorrent",
    "telegram": "Telegram", "telegram 生态": "Telegram",
    "steam": "Steam", "steam 生态": "Steam",
    "edk2": "EDK2", "edk2 生态": "EDK2",
    "fcitx": "fcitx", "fcitx 生态": "fcitx", "fcitx5": "fcitx",
    "electron": "Electron", "electron 生态": "Electron",
    "flutter": "Flutter", "flutter 生态": "Flutter",
    "mpv": "MPV", "mpv 播放器生态": "MPV", "mpv播放器生态": "MPV",
    "qbittorrent": "qBittorrent", "qbittorrent 生态": "qBittorrent", "qbit": "qBittorrent",
    "hyprland": "Hyprland", "hyprland 生态": "Hyprland", "hypr": "Hyprland",
    "obsidian": "Obsidian", "obsidian 生态": "Obsidian",
    "neovim": "Neovim", "neovim 生态": "Neovim", "nvim": "Neovim",
    "vscode": "VS Code", "vscode 生态": "VS Code", "vs code": "VS Code",
    "home assistant": "Home Assistant", "home assistant 生态": "Home Assistant",
    "homeassistant": "Home Assistant", "hass": "Home Assistant",
    "zsh": "Zsh / Oh-My-Zsh", "zsh 生态": "Zsh / Oh-My-Zsh",
    "oh-my-zsh": "Zsh / Oh-My-Zsh", "oh-my-zsh 生态": "Zsh / Oh-My-Zsh",
    "starship": "Starship", "starship 生态": "Starship",
    "alacritty": "Alacritty", "alacritty 生态": "Alacritty",
    "kitty": "Kitty", "kitty 生态": "Kitty",
    "i3": "i3 / Sway", "i3 生态": "i3 / Sway", "sway": "i3 / Sway", "sway 生态": "i3 / Sway",
    "awesomewm": "AwesomeWM", "awesome 生态": "AwesomeWM", "awesomewm 生态": "AwesomeWM",
    "awesome wm": "AwesomeWM",
    "react": "React", "react 生态": "React",
    "vue": "Vue", "vue 生态": "Vue", "nuxt": "Vue", "nuxt 生态": "Vue",
    "tailwind": "Tailwind CSS", "tailwind 生态": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS", "tailwindcss 生态": "Tailwind CSS",
    # 新发现生态
    "firefox": "Firefox", "firefox 生态": "Firefox",
    "git": "Git", "git 生态": "Git",
    "magisk": "Magisk", "magisk 生态": "Magisk",
    "bit-torrent": "BitTorrent", "bittorrent": "BitTorrent", "bt": "BitTorrent",
    "airplay": "AirPlay",
    "hms": "HMS",
    "edk2": "EDK2",
    # OBS / 新生态
    "obs": "OBS Studio", "obs studio": "OBS Studio", "obs-studio": "OBS Studio",
    "obs 生态": "OBS Studio", "obsstudio": "OBS Studio",
    "streamfx": "OBS Studio", "input-overlay": "OBS Studio",
    "scoop": "Scoop", "scoop 生态": "Scoop",
    "typora": "Typora", "typora 生态": "Typora",
    "moonlight": "Moonlight / Sunshine", "sunshine": "Moonlight / Sunshine",
    "moonlight 生态": "Moonlight / Sunshine", "sunshine 生态": "Moonlight / Sunshine",
    "apollo": "Moonlight / Sunshine",
    "mihon": "Mihon / Tachiyomi", "tachiyomi": "Mihon / Tachiyomi",
    "mihon 生态": "Mihon / Tachiyomi", "tachiyomi 生态": "Mihon / Tachiyomi",
    "emby": "Emby / Jellyfin", "jellyfin": "Emby / Jellyfin",
    "emby 生态": "Emby / Jellyfin", "jellyfin 生态": "Emby / Jellyfin",
    "emby/jellyfin": "Emby / Jellyfin",
    "bilibili": "Bilibili", "bilibili 生态": "Bilibili", "b站": "Bilibili",
    "stable diffusion": "Stable Diffusion", "stable diffusion 生态": "Stable Diffusion",
    "sd-webui": "Stable Diffusion", "comfyui": "Stable Diffusion",
    "comfyui 生态": "Stable Diffusion", "sd": "Stable Diffusion",
    "aria2": "Aria2", "aria2 生态": "Aria2", "ariang": "Aria2",
    "yt-dlp": "yt-dlp", "yt-dlp 生态": "yt-dlp", "youtube-dl": "yt-dlp",
    "alist": "AList", "alist 生态": "AList", "openlist": "AList",
    "tailscale": "Tailscale / WireGuard", "wireguard": "Tailscale / WireGuard",
    "tailscale 生态": "Tailscale / WireGuard", "wireguard 生态": "Tailscale / WireGuard",
    "nushell": "Nushell", "nushell 生态": "Nushell",
    "homebrew": "Homebrew", "homebrew 生态": "Homebrew", "brew": "Homebrew",
    "rvc": "RVC / AI Voice", "so-vits-svc": "RVC / AI Voice", "fish-speech": "RVC / AI Voice",
    "rvc 生态": "RVC / AI Voice", "ai voice": "RVC / AI Voice",
    "sillytavern": "SillyTavern", "sillytavern 生态": "SillyTavern",
    "notion": "Notion / AppFlowy", "appflowy": "Notion / AppFlowy", "affine": "Notion / AppFlowy",
    "notion 生态": "Notion / AppFlowy", "appflowy 生态": "Notion / AppFlowy",
    "rss": "RSS / 阅读", "rss 生态": "RSS / 阅读", "阅读": "RSS / 阅读",
    "rsshub": "RSS / 阅读", "folo": "RSS / 阅读",
    "localsend": "localsend", "localsend 生态": "localsend",
    "ventoy": "Ventoy", "ventoy 生态": "Ventoy",
    "screentogif": "ScreenToGif", "screentogif 生态": "ScreenToGif",
    "typst": "Typst", "typst 生态": "Typst",
    "ehviewer": "EhViewer", "ehviewer 生态": "EhViewer",
    "picacomic": "PicaComic", "picacomic 生态": "PicaComic",
    "anime4k": "Anime4K", "anime4k 生态": "Anime4K",
    "rufus": "rufus", "rufus 生态": "rufus",
    "spotube": "Spotube", "spotube 生态": "Spotube",
    "animeko": "open-ani / Animeko", "open-ani": "open-ani / Animeko",
    "animeko 生态": "open-ani / Animeko",
    "czkawka": "Czkawka", "czkawka 生态": "Czkawka",
    "trafficmonitor": "TrafficMonitor", "trafficmonitor 生态": "TrafficMonitor",
    "scrcpy": "QtScrcpy / Scrcpy", "qtscrcpy": "QtScrcpy / Scrcpy",
    "scrcpy 生态": "QtScrcpy / Scrcpy",
    "trollstore": "TrollStore", "trollstore 生态": "TrollStore",
    "kernelsu": "KernelSU", "kernelsu 生态": "KernelSU",
    "lsposed": "LSPosed", "lsposed 生态": "LSPosed", "xposed": "LSPosed",
    "electron": "Electron", "electron 生态": "Electron",
}

# ==================== 全字段归一化映射 ====================
# LLM 返回的分类字段都是自由文本或半约束，容易产生空格/中英文/大小写变体。
# 后处理阶段用这些表统一映射到标准名称。

# 从规则字典自动生成标准名称集合
PLATFORM_STANDARD_NAMES = list(PLATFORM_RULES.keys()) + ["其他 / 未分类"]
TYPE_STANDARD_NAMES = list(TYPE_RULES.keys()) + ["其他 / 未分类"]
ECOLOGY_ROLE_STANDARD_NAMES = list(ECOLOGY_ROLES.keys()) + ["其他 / Other"]

PLATFORM_ALIASES = {
    "android": "Android", "安卓": "Android",
    "ios": "iOS",
    "windows": "Windows", "win32": "Windows", "win64": "Windows",
    "linux": "Linux",
    "macos": "macOS", "mac-os": "macOS", "osx": "macOS", "darwin": "macOS", "apple": "macOS",
    "web": "Web", "browser": "Web",
    "跨平台": "跨平台", "cross-platform": "跨平台", "multi-platform": "跨平台",
    "其他/未分类": "其他 / 未分类", "未分类": "其他 / 未分类", "other": "其他 / 未分类",
}

TYPE_ALIASES = {
    "应用/app": "应用 / App", "app": "应用 / App", "application": "应用 / App",
    "framework": "框架 / Framework", "library": "框架 / Framework",
    "tool": "工具 / Tool", "utility": "工具 / Tool",
    "web前端": "Web 前端", "web 前端": "Web 前端", "frontend": "Web 前端",
    "web后端": "Web 后端", "web 后端": "Web 后端", "backend": "Web 后端",
    "移动端app": "移动端 App", "移动端 app": "移动端 App", "mobile": "移动端 App",
    "桌面gui": "桌面 GUI", "桌面 gui": "桌面 GUI", "desktop": "桌面 GUI",
    "cli/终端": "CLI / 终端", "cli 终端": "CLI / 终端", "命令行": "CLI / 终端",
    "游戏": "游戏", "game": "游戏",
    "ide": "编辑器 / IDE", "editor": "编辑器 / IDE",
    "awesome": "资源合集 / Awesome", "list": "资源合集 / Awesome", "合集": "资源合集 / Awesome",
    "compiler": "语言 / Compiler", "interpreter": "语言 / Compiler",
    "monitoring": "监控 / 可视化", "dashboard": "监控 / 可视化", "可视化": "监控 / 可视化",
    "workflow": "自动化 / 工作流", "automation": "自动化 / 工作流", "工作流": "自动化 / 工作流",
    "notes": "笔记 / 知识管理", "wiki": "笔记 / 知识管理", "知识管理": "笔记 / 知识管理",
    "algorithm": "算法 / 学习", "tutorial": "算法 / 学习", "学习": "算法 / 学习",
    "dotfiles": "配置 / Dotfiles", "config": "配置 / Dotfiles",
    "其他/未分类": "其他 / 未分类", "未分类": "其他 / 未分类", "other": "其他 / 未分类",
}

ECOLOGY_ROLE_ALIASES = {
    "核心": "核心 / Core", "core": "核心 / Core", "kernel": "核心 / Core", "engine": "核心 / Core",
    "gui前端": "GUI 前端 / Client", "gui 前端": "GUI 前端 / Client", "gui前端/client": "GUI 前端 / Client",
    "client": "GUI 前端 / Client", "frontend": "GUI 前端 / Client", "app": "GUI 前端 / Client",
    "配置": "配置 / Config", "config": "配置 / Config", "configuration": "配置 / Config", "dotfiles": "配置 / Config",
    "脚本": "脚本 / Script", "script": "脚本 / Script", "lua": "脚本 / Script", "automation": "脚本 / Script",
    "主题": "主题 / Theme", "theme": "主题 / Theme", "skin": "主题 / Theme", "colorscheme": "主题 / Theme",
    "插件": "插件 / Plugin", "plugin": "插件 / Plugin", "extension": "插件 / Plugin", "addon": "插件 / Plugin",
    "规则集": "规则集 / Rules", "rules": "规则集 / Rules", "rule": "规则集 / Rules", "filter": "规则集 / Rules",
    "webui": "Web UI / Dashboard", "web ui": "Web UI / Dashboard", "web-ui": "Web UI / Dashboard",
    "dashboard": "Web UI / Dashboard", "panel": "Web UI / Dashboard",
    "api封装": "API 封装 / Wrapper", "api 封装": "API 封装 / Wrapper", "apiwrapper": "API 封装 / Wrapper",
    "wrapper": "API 封装 / Wrapper", "binding": "API 封装 / Wrapper", "sdk": "API 封装 / Wrapper",
    "教程": "教程 / Guide", "guide": "教程 / Guide", "tutorial": "教程 / Guide", "awesome": "教程 / Guide",
    "其他": "其他 / Other", "other": "其他 / Other", "null": "其他 / Other", "none": "其他 / Other", "-": "其他 / Other",
}

# 标准生态名称集合（用于系统提示限制和验证）
ECOLOGY_STANDARD_NAMES = list(ECOLOGY_RULES.keys()) + [
    "独立项目", "AI/ML", "Android", "Apple", "BitTorrent",
    "AirPlay", "HMS", "EDK2", "Firefox", "Git", "Magisk",
]
